djangosite/mysite/urls.py
# here v import urls.py file of each apps
# and set the urls in urlpatterns list.


from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # when v navigate to 'pollsapp/'.  it in
    # includes pollsapp.urls file, and inthat urls.py file,
    # it calls the views.index. and render the pollsapp/index.html

    path('pollsapp/', include('pollsapp.urls')),


]

djangosite/pollsapp/urls.py
from django.urls import path

from . import views

app_name = 'pollsapp'

# create a route and calls the view function.
# and give a name for that route.

# here v capture an integer parameter 'question_id' from url so v use angle brackets,
# and this 'question_id' value is passed as an argument  to the parameter
# 'question_id' in views.detail function.

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
]

djangosite/pollsapp/models.py
from django.db import models


# Create your models here.
class Questions(models.Model):
    # Each model has a number of class variables, each of which
    # represents a database field in the model.
    # here CharField and DateTimeField r thr type of that field.
    # each model will have an id created automatically.
    # and it is auto incremented.
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    # Choice model has a foreign key which is related to primary key of
    # Question model.
    # this tell that each choice is related to a question.
    # on_delete = models.CASCADE means, if a question is deleted
    # then its choice also deleted.
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# here v specified the models to be created, next to create this . Edit the mysite/settings.py file and add that
# dotted path to the INSTALLED_APPS models for our app, first need to include our app in
# the project, To include the app in our project, we need to add a reference to its configuration class in the
# INSTALLED_APPS setting. The PollsConfig class is in the pollsapp/apps.py file, so its dotted path is
# 'pollsapp.apps.PollsConfig. . Edit the mysite/settings.py file and add that dotted path to the INSTALLED_APPS.

djangosite/pollsapp/views.py
from django.shortcuts import render

from django.http import HttpResponse, Http404

# import models
from .models import Questions, Choice


# Create your views here.
#
def index(request):

    # here v order the questions in descending order based on publication date
    # and fetches 5 records. thud we get queryset of questions
    latest_question_list = Questions.objects.order_by('-pub_date')[:5]

    # later v pass this queryset as a dictionary to the template.
    context = {'latest_question_list': latest_question_list}
    return render(request, 'pollsapp/index.html', context)
    # now we can access the data in index.html file


# need to display a specific question and its choices. for tat create a view named detail
def detail(request, question_id):
    pass

    # here v try to get the question from Questions and pass that question as dictionary to the
    # template v render and if no questions exist it raises an http404 error
    # here DoesNotExist is a class of model Questions
    try:
        q = Questions.objects.get(pk=question_id)
    except Questions.DoesNotExist:
        raise Http404('Question not exist')
    return render(request, 'pollsapp/results.html', {'question': q})

djangosite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <!-- we may need diff titles for diff pages -->
    <!-- for that v can use a syntax like below -->
    <title>PollsApp {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
            <div class="container">
            
                    <a class="navbar-brand" href="#">Poll Site</a>
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                        <!-- to get the hamburger icon -->
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item"><a class="nav-link"href="#">Home</a></li>
                            <li class="nav-item"><a href="#" class="nav-link">About</a></li>
                            <li class="nav-item"><a href="#" class="nav-link">Services</a></li>
                            <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
                        </ul>
                    </div>
            </div>
    </nav>

    <div class="container">
        <!-- make a row -->
        <div class="row">
            <!-- in that row v make a 6 medium columns  and make it center -->
            <div class="col-md-6 m-auto">
                <!-- with in this div v want to display the index.html template or any other template -->

                <!-- use syntax used bfore -->
                {% block content %}{% endblock %}

            </div>
            
        </div>
    </div>

    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</body>
</html>

djangosite/templates/pollsapp/index.html
<!-- here v need to extend the base.html -->
<!-- then only the layout given in the base html file will came to effect here -->

{% extends 'base.html' %}
{% block content %}
        <h1 class="text-center mb-3">Poll Questions</h1>
        {% if latest_question_list %}
            {% for q in  latest_question_list%}
                <div class="card mb-3">
                    <div class="card-body">
                        <p class="lead">
                            <!-- outputs each questions in the latest_question_list -->
                            {{q.question_text}}
                        </p>

                        <!-- here v place a link to vote that goes to vote page-->

                        <!-- so v use template syntax for url instead of regular link -->

                        <!-- first give url, later give appname and view function to be loaded as a key:value and give the id for that specific question v need -->

                        <a href="{% url 'pollsapp:detail' q.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                    </div>
                </div> 
            {% endfor %}
        {% else %}
            <p>No Polls done yet</p>
        {% endif %}
{% endblock %}